name: Create Version Tag and Release

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Make artifact"]
    types:
      - completed

jobs:
  make-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.workflow_run.head_branch }}
          release_name: Release ${{ github.event.workflow_run.head_branch }}
          body: |
            $(cat changelog/${{ github.event.workflow_run.head_branch }}.md)
          draft: false
          prerelease: false